### ISSUE TITLE
Missing files in solution

### ISSUE THREAD

**Issue by fernandoagomezf** [henrypp/matrix#11]
Hi, I downloaded the source code and opened it with Visual Studio. However, the solution file is expecting the following files: 

- rapp.hpp / rapp.cpp
- rconfig.hpp
- routine.hpp / routine.cpp
- rstring.hpp / rstring.cpp

Furthermore, some source code files reference these files, so it wouldn't even compile if I remove their references from the solution. Is some additional step needed to compile this code?

Thanks in advance!

**Comment by stephengeorgewest** [comment]
I just happened to run into this too. routine is located at: [../routine](https://github.com/henrypp/routine). It is shared across severeral of these projects. You can pull that project down as well, and it should compile. But, yeah, the solution should include it.

**Comment by fernandoagomezf** [comment]
Ah, I see, they're in a different repository. Will download them manually then. Thanks!!

**Comment by fernandoagomezf** [comment]
Yes, that did the trick, managed to compile and run it in VC++ 2019.  Just put the source files in the routine files in the src directory and changed the sln references. Thanks!
