### ISSUE TITLE
Triple monitor cuts the screensaver

### ISSUE THREAD

**Issue by markdza** [henrypp/matrix#3]
I have a 3 monitor set up, where the ones on the left and right are in portrait mode and the one in the middle is in landscape. It is similar to this picture: https://i.imgur.com/361NIHk.jpg

When the v1.3 x64 screensaver was set up, it looked cool on the middle monitor (takes up the whole screen) but because my other two monitors are in portrait mode, the screensaver cuts off approx. 50% on those monitors (only shows in the top approx. 50% of the monitor).

Please fix

**Comment by jdroo** [comment]
same issue, tho it seems to be using the size of my 1st monitor, i have 3, tho the ones on the left and right are smaller, my middle monitor is a lot bigger, and so the bigger one seems to just match the size of the screensaver on the smaller monitor.

**Comment by mrnettek** [comment]
Same issue. Where is the rest of the source code? The zip appears to be missing rapp.cpp, routine.cpp, rconfig.h, and rstring.cpp. I would like to just fix and recompile.

**Comment by henrypp** [comment]
@mrnettek `../routine/`
