### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by iglonator** [henrypp/matrix#5]
The installer doesn't install anything. When I put cmd /k to the end of the .bat to see what's wrong, the cmd shows: The syntax of the command is incorrect. So nothing is being installed... How could I make this work, I'd really love a matrix screensaver and this one seems really good.

**Comment by henrypp** [comment]
What do you do?

**Comment by henrypp** [comment]
Maybe you have no rights, maybe something else. Try to append `pause` at the eol of **install.bat**
