### ISSUE TITLE
cannot compile from source (VSC2017) - missing files: rapp routine rconfig rstring 

### ISSUE THREAD

**Issue by githubuser181226** [henrypp/matrix#7]
hi.
I'm trying to compile the program from source. I'm using VS2017 Community.

I'm getting these errors while building the solution:
Error	C1083	Cannot open source file: '..\routine\rapp.cpp': No such file or directory	matrix	C:\Users\VS2017\Desktop\matrix-master\c1xx	1	
Error	C1083	Cannot open source file: '..\routine\routine.cpp': No such file or directory	matrix	C:\Users\VS2017\Desktop\matrix-master\c1xx	1	
Error	C1083	Cannot open source file: '..\routine\rstring.cpp': No such file or directory	matrix	C:\Users\VS2017\Desktop\matrix-master\c1xx	1	
Error	C1083	Cannot open include file: 'rapp.hpp': No such file or directory	matrix	c:\users\vs2017\desktop\matrix-master\src\main.cpp	9	

there are no coresponding files inside the package.

please advise.

edit: ok, I've found your "routine" package =P now everything builds without a problem. thanks.

**Comment by fernandoagomezf** [comment]
Hi, I'm having the same issue. How was it solved?

**Comment by githubuser181226** [comment]
> 
> 
> Hi, I'm having the same issue. How was it solved?

hi. if you refer to my OP here's my own modded version of the screensaver.
I think I made only 2 changes compared to the original source code, that is I set the default animation speed and character color (hue) inside main.hpp (lines 35 and 39) and rebuilt the project.

if you try to compile from source and you get errors similiar to those I mentioned above you probably are missing some additional package. in my case it was "routine" package which you should find on the author's github/website.

I attatched my modded version. I compiled it successfuly using VS2017. there are ready to use .scr files (32 and 64 bit) in there.

hope this helps. cheers.

[matrix-red181226-VS2017.zip](https://github.com/henrypp/matrix/files/3124895/matrix-red181226-VS2017.zip)
